# Generated by Django 5.1.1 on 2025-01-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(blank=True, default='pofile_pictures/default_pfp.png', upload_to='profile_pictures/'),
        ),
    ]
