# Generated by Django 5.1.1 on 2025-01-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_anime_vector_rep'),
        ('profiles_api', '0003_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_anime',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.anime'),
        ),
    ]
