# Generated by Django 5.1.3 on 2025-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles_api", "0004_alter_userprofile_favourite_anime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
