# Generated by Django 5.1.1 on 2025-01-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations_api', '0002_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecommendationhistory',
            name='recommended_shows',
        ),
        migrations.AddField(
            model_name='userrecommendationhistory',
            name='recommended_shows',
            field=models.JSONField(default=list),
        ),
    ]
