# Generated by Django 5.1.3 on 2024-11-24 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_english', models.CharField(blank=True, max_length=255)),
                ('score', models.FloatField(blank=True, null=True)),
                ('ranked', models.IntegerField(blank=True, null=True)),
                ('members', models.IntegerField(blank=True, null=True)),
                ('scored_by', models.FloatField(blank=True, null=True)),
                ('favorites', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True)),
                ('aired', models.CharField(blank=True, max_length=100)),
                ('duration_per_ep', models.CharField(blank=True, max_length=100)),
                ('imagelink', models.TextField(blank=True, default='un-available')),
                ('total_episodes', models.FloatField(blank=True, null=True)),
                ('premiered', models.CharField(blank=True, max_length=100)),
                ('watching', models.IntegerField(blank=True, null=True)),
                ('completed', models.IntegerField(blank=True, null=True)),
                ('on_hold', models.IntegerField(blank=True, null=True)),
                ('dropped', models.IntegerField(blank=True, null=True)),
                ('plan_to_watch', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('scored_10_by', models.FloatField(blank=True, null=True)),
                ('scored_9_by', models.FloatField(blank=True, null=True)),
                ('scored_8_by', models.FloatField(blank=True, null=True)),
                ('scored_7_by', models.FloatField(blank=True, null=True)),
                ('scored_6_by', models.FloatField(blank=True, null=True)),
                ('scored_5_by', models.FloatField(blank=True, null=True)),
                ('scored_4_by', models.FloatField(blank=True, null=True)),
                ('scored_3_by', models.FloatField(blank=True, null=True)),
                ('scored_2_by', models.FloatField(blank=True, null=True)),
                ('scored_1_by', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown Demographic', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown Genre', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown Rating', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown Source', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown Studio', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown Type', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='demographic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='core.demographic'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='animes', to='core.genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='core.rating'),
        ),
        migrations.AddField(
            model_name='anime',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='core.source'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='core.studio'),
        ),
        migrations.AddField(
            model_name='anime',
            name='typeof',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='core.typeof'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, default=1)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('favourite_anime', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite_anime', to='core.anime')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'anime'), name='unique_saved_anime')],
            },
        ),
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'anime'), name='unique_watch_later')],
            },
        ),
    ]
