# Generated by Django 5.1.1 on 2025-01-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='vector_rep',
            field=models.JSONField(default=[]),
        ),
    ]
