# Generated by Django 5.1.1 on 2025-01-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anime_vector_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='vector_rep',
            field=models.JSONField(default=[], null=True),
        ),
    ]
