# Generated by Django 5.1.1 on 2025-01-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_character_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='demographic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='demography', to='core.demographic'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(blank=True, to='core.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='core.rating'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='core.source'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='core.studio'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='typeof',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeof', to='core.typeof'),
        ),
    ]
