name: Repo Visualizer

on:
  push:
    branches:
      - main

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate repo visualization
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: repo-diagram.svg
          branch: main

      - name: Upload visualizer diagram
        uses: actions/upload-artifact@v4
        with:
          name: repo-diagram
          path: repo-diagram.svg
          retention-days: 30
