name: Repo Visualizer

on:
  push:
    branches:
      - main

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate repo visualization
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: repo-diagram.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-diagram
          path: repo-diagram.svg
          retention-days: 30

      - name: Commit diagram to update branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Delete local branch if it exists
          git branch -D repo-visualizer-update || echo "branch does not exist"
          
          # Create/update branch locally
          git checkout -B repo-visualizer-update
          
          git add repo-diagram.svg
          git commit -m "chore(diagram): update repo visualization" || echo "No changes to commit"
          
          # Push branch to remote (creates it if missing)
          git push -u origin repo-visualizer-update --force

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: repo-visualizer-update
          commit-message: "chore(diagram): update repo visualization"
          title: "chore: update repo visualization"
          body: "This PR automatically updates the repo visualization diagram."
          base: main
          labels: |
            automated
            visualization
